const A = "/Users/Rensley/Desktop/pulseStudio/PulseStudio/app/";
globalThis.localStorage = { getItem:()=>null, setItem:()=>{}, removeItem:()=>{} };
const { sharedStudio } = await import(A+"shared/auth/studio.js");
const { fixtureSetFrom } = await import(A+"products/d-reengagement/live-studio.js");
const { findQuietMembers, todayDayNumber } = await import(A+"products/d-reengagement/logic.js");
const { proposedRules } = await import(A+"products/d-reengagement/config.js");
const ds = sharedStudio();
const data = fixtureSetFrom(ds, []);
const today = todayDayNumber(data.timezone);
const res = findQuietMembers(data, today, proposedRules);
console.log("flagged names:", res.flagged.map(f=>f.member.display_name+" ("+f.daysSince+"d)"));
console.log("first 6 sign-in choices:", ds.members.slice(0,6).map(m=>m.displayName));
