#!/usr/bin/env node
/* Pulse Studio — the brief-mirror gate. TEAM-OWNED.
 *
 * WHY THIS EXISTS: the team does not all run the same assistant, so every
 * folder's brief exists twice — `CLAUDE.md`, read natively by Claude Code,
 * and `AGENTS.md`, read natively by OpenAI Codex and most general agents.
 * The root brief states the rule: "AGENTS.md — a byte-equivalent mirror of
 * the sibling CLAUDE.md ... If the two ever disagree, CLAUDE.md wins and
 * the mirror needs regenerating."
 *
 * Nothing checked it, and the drift it invites is the worst-placed kind: a
 * brief governs every edit made in its folder, so a stale mirror does not
 * cause one wrong change, it quietly authorises a stream of them. The team
 * has already been bitten once by a second copy of a law going stale — the
 * always-on Cursor rule told people "backgrounds are black or white only"
 * for weeks after the colour law began allowing an accessible custom pair,
 * and `.cursor/rules/team.mdc` now carries that story instead of the law.
 *
 * AGENTS.md IS THE FILE THE OTHER ASSISTANTS EDIT, which is what makes this
 * more than hypothetical. An agent reading AGENTS.md natively and asked to
 * correct a brief will correct the file in front of it. That edit is
 * invisible to Claude Code, survives review, and is erased without trace
 * the next time anybody runs the sync script.
 *
 * WHAT IT DOES: regenerates every mirror in memory, exactly as
 * scripts/sync-agent-briefs.sh writes it, and compares. It never writes —
 * a gate that repaired the drift would hide it, and the point is that
 * somebody made an edit in the wrong file and needs to know which.
 *
 * HONEST LIMITS. It compares bytes, so it cannot tell an intentional
 * improvement made in the wrong file from a mistake — it says only that
 * they differ and which one wins. And it knows nothing about the
 * `.cursor/rules/*.mdc` files, which are deliberately NOT mirrors: they are
 * thin pointers, and a rule that forced them to match would recreate the
 * duplication they exist to avoid.
 *
 * Run: node scripts/check-mirrors.mjs   (also runs inside `npm run check`)
 * Prove it still works: node scripts/check-mirrors.mjs --self-test
 */

import { execFileSync } from "node:child_process";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { isCommand } from "./is-command.mjs";

const IS_COMMAND = isCommand(import.meta.url);
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/* The two lines sync-agent-briefs.sh writes above the copied brief, and the
 * blank line after them.
 *
 * THIS IS A SECOND COPY OF A SHAPE THE SHELL SCRIPT ALSO DEFINES, which is
 * the duplication this repo keeps paying for — a contrast formula written
 * twice, "today" written three times, ten copies of one guard. It cannot be
 * shared: one file is bash and the other is JavaScript. So it is CHECKED
 * instead, by headerMatchesScript() below, which reads the script and
 * compares. Two copies that are compared are not the same problem as two
 * copies that are not. */
export const MIRROR_HEADER = [
  "> MIRROR of the CLAUDE.md in this folder, generated by scripts/sync-agent-briefs.sh.",
  "> Edit CLAUDE.md and re-run the script; if the two ever differ, CLAUDE.md wins.",
  "",
].join("\n");

/** The header lines the shell script actually echoes, read from its source.
 *  Returns null when they cannot be found, which is itself a mismatch: a
 *  script this gate can no longer read is one it can no longer agree with. */
export function headerFromScript(scriptText) {
  const echoed = [...scriptText.matchAll(/^\s*echo\s+"(>[^"]*)"/gm)].map((m) => m[1]);
  if (echoed.length !== 2) return null;
  return `${echoed.join("\n")}\n`;
}

/** "" when the gate's copy of the header matches the script's. */
export function headerMatchesScript(scriptText) {
  const fromScript = headerFromScript(scriptText);
  if (fromScript === null) {
    return "could not find the two header lines in sync-agent-briefs.sh";
  }
  return fromScript === MIRROR_HEADER
    ? ""
    : "the header this gate expects is not the header the script writes";
}

/** What AGENTS.md should contain, given its sibling CLAUDE.md. */
export function expectedMirror(briefText) {
  return `${MIRROR_HEADER}\n${briefText}`;
}

/** "" when the mirror is right, otherwise what is wrong with it. */
export function mirrorProblem(briefText, mirrorText) {
  if (mirrorText === null) return "no AGENTS.md beside it";
  const expected = expectedMirror(briefText);
  if (mirrorText === expected) return "";
  if (!mirrorText.startsWith(MIRROR_HEADER)) return "the generated header is missing or altered";
  return "the brief and its mirror have diverged";
}

/* ---------- the self-test ---------- */

function selfTest() {
  const brief = "# A brief\n\nOne law.\n";
  const planted = [
    ["a freshly generated mirror is right", brief, expectedMirror(brief), ""],
    ["a missing mirror is caught", brief, null, "no AGENTS.md beside it"],
    ["a mirror with no header is caught", brief, brief, "the generated header is missing or altered"],
    ["an edited header is caught", brief,
      expectedMirror(brief).replace("CLAUDE.md wins", "AGENTS.md wins"),
      "the generated header is missing or altered"],
    /* The case this gate is for: somebody improved the brief in the mirror,
     * which is the file their assistant reads. */
    ["a body edited only in the mirror is caught", brief,
      expectedMirror("# A brief\n\nOne law, revised.\n"), "the brief and its mirror have diverged"],
    ["a body edited only in the brief is caught", "# A brief\n\nTwo laws.\n",
      expectedMirror(brief), "the brief and its mirror have diverged"],
    /* Whitespace is a difference: the mirror is byte-equivalent or it is
     * not, and a trailing newline is exactly the kind of near-miss a
     * hand-edit leaves behind. */
    ["a trailing newline difference is still a difference", brief,
      `${expectedMirror(brief)}\n`, "the brief and its mirror have diverged"],
  ];

  let failed = 0;

  /* The gate's copy of the header, against the script that writes it. */
  const headerCases = [
    ["the real script's header is the one this gate expects",
      readFileSync(join(ROOT, "scripts/sync-agent-briefs.sh"), "utf8"), ""],
    ["a script echoing a different header is caught",
      'echo "> MIRROR of something else."\necho "> Second line."', 
      "the header this gate expects is not the header the script writes"],
    ["a script with no header lines is caught", "echo hello",
      "could not find the two header lines in sync-agent-briefs.sh"],
    ["a script echoing only one is caught", 'echo "> Just the one."',
      "could not find the two header lines in sync-agent-briefs.sh"],
  ];
  for (const [label, scriptText, want] of headerCases) {
    const got = headerMatchesScript(scriptText);
    if (got !== want) {
      failed += 1;
      console.error(`  self-test MISS — ${label}: wanted ${JSON.stringify(want)}, got ${JSON.stringify(got)}`);
    }
  }

  for (const [label, briefText, mirrorText, want] of planted) {
    const got = mirrorProblem(briefText, mirrorText);
    if (got !== want) {
      failed += 1;
      console.error(`  self-test MISS — ${label}: wanted ${JSON.stringify(want)}, got ${JSON.stringify(got)}`);
    }
  }
  console.log(`self-test: ${planted.length + headerCases.length} planted cases, ${planted.length + headerCases.length - failed} behaved, ${failed} did not.`);
  console.log(
    failed === 0
      ? "self-test PASSED — the gate can still fail."
      : "self-test FAILED — the gate is blind.",
  );
  process.exit(failed === 0 ? 0 : 1);
}

/* ---------- the gate ---------- */

function run() {
  /* Before anything else: does this gate still agree with the script whose
   * output it is judging? If not, every verdict below is measured against
   * the wrong shape. */
  const scriptPath = join(ROOT, "scripts/sync-agent-briefs.sh");
  const headerProblem = existsSync(scriptPath)
    ? headerMatchesScript(readFileSync(scriptPath, "utf8"))
    : "scripts/sync-agent-briefs.sh is missing";
  if (headerProblem !== "") {
    console.error(
      `check-mirrors: ${headerProblem}. This gate keeps its own copy of the two lines the script writes, ` +
        "because one file is bash and the other JavaScript and neither can import the other. A copy that " +
        "has drifted judges every mirror against a shape nothing produces — fix both, in the same change.",
    );
    process.exit(1);
  }

  const briefs = execFileSync("git", ["-C", ROOT, "ls-files", "*CLAUDE.md"], { encoding: "utf8" })
    .split("\n").map((f) => f.trim()).filter((f) => f !== "");

  const problems = [];

  /* WALKING THE BRIEFS ALONE CANNOT SEE A MIRROR OF NOTHING. Every check
   * below starts from a CLAUDE.md, so an AGENTS.md whose sibling was
   * deleted or renamed is invisible to all of them — and that file is the
   * one a non-Claude assistant reads. It would go on being read, by a tool
   * with no way to know its source is gone, and the sync script would never
   * touch it again. Iterate the other side too. */
  const mirrors = execFileSync("git", ["-C", ROOT, "ls-files", "*AGENTS.md"], { encoding: "utf8" })
    .split("\n").map((f) => f.trim()).filter((f) => f !== "");
  for (const mirror of mirrors) {
    const brief = join(dirname(mirror), "CLAUDE.md");
    if (!briefs.includes(brief)) {
      problems.push({
        brief,
        mirror,
        problem: "there is no CLAUDE.md beside it, so it mirrors nothing",
        orphan: true,
      });
    }
  }
  for (const brief of briefs) {
    const mirror = join(dirname(brief), "AGENTS.md");
    const mirrorPath = join(ROOT, mirror);
    const mirrorText = existsSync(mirrorPath) ? readFileSync(mirrorPath, "utf8") : null;
    const problem = mirrorProblem(readFileSync(join(ROOT, brief), "utf8"), mirrorText);
    if (problem !== "") problems.push({ brief, mirror, problem });
  }

  console.log(
    `check-mirrors: ${briefs.length} folder brief${briefs.length === 1 ? "" : "s"} compared with the AGENTS.md ` +
      `beside them, and ${mirrors.length} mirror${mirrors.length === 1 ? "" : "s"} checked for a brief to mirror.`,
  );
  if (problems.length === 0) {
    console.log("check-mirrors: every mirror matches the brief it copies. PASS");
    return;
  }
  for (const { brief, mirror, problem, orphan } of problems) {
    /* An orphan needs different advice: telling somebody to move their edit
     * into a file that does not exist is worse than saying nothing. */
    console.error(
      orphan
        ? `  ${mirror} · ${problem}. Nothing generates it any more and no tool will update it, but the ` +
            "assistants that read AGENTS.md natively will go on reading it. Either restore " +
            `${brief} and run \`bash scripts/sync-agent-briefs.sh\`, or delete the mirror with it.`
        : `  ${mirror} · ${problem}. The brief is the law and the mirror is generated from it, so an edit ` +
            `made HERE is lost the next time anybody runs the sync script. Move the change into ${brief}, ` +
            "then run `bash scripts/sync-agent-briefs.sh`.",
    );
  }
  console.error(
    `check-mirrors: ${problems.length} brief${problems.length === 1 ? "" : "s"} out of step with its mirror. FAIL`,
  );
  process.exit(1);
}

if (IS_COMMAND) {
  if (process.argv.includes("--self-test")) selfTest();
  else run();
}
