#!/usr/bin/env bash
# Pulse Studio — regenerate every AGENTS.md as a mirror of its sibling
# CLAUDE.md. The content is law, the filename is not: Claude Code reads
# CLAUDE.md natively; OpenAI Codex and most general agents read AGENTS.md.
# One canonical file per folder (CLAUDE.md), one generated mirror, zero
# drift. Run from anywhere: bash scripts/sync-agent-briefs.sh
set -euo pipefail
cd "$(dirname "$0")/.."
find . -name CLAUDE.md -not -path "./node_modules/*" | sort | while read -r brief; do
  dir=$(dirname "$brief")
  {
    echo "> MIRROR of the CLAUDE.md in this folder, generated by scripts/sync-agent-briefs.sh."
    echo "> Edit CLAUDE.md and re-run the script; if the two ever differ, CLAUDE.md wins."
    echo
    cat "$brief"
  } > "$dir/AGENTS.md"
  echo "mirrored $brief -> $dir/AGENTS.md"
done
